### ISSUE TITLE
Confirmation Code masterregister.php

### ISSUE THREAD

**Issue by xVaan** [acelabini/FluxCP-MasterAccount#1]
**Confirmation Code masterregister.php**

If RequireEmailConfirm is true, when you register a master account the confirm_code is not registered properly in **cp_users** table, causing a glitch.

**Comment by acelabini** [comment]
Hi @xVaan, thank you for reporting this bug. 

Resolved @ https://github.com/acelabini/FluxCP-MasterAccount/commit/da7a11be3b1c25f3772af57118cbcc898fd69f9f
